package com.wangsd.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-12-19T11:33:36.503+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://cxfDemo.wangsd.com/", name = "HelloWorld")
public interface HelloWorld {

    @WebMethod(operationName = "SayHiToUserList")
    public java.util.List<java.lang.String> sayHiToUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.wangsd.client.User> arg0
    );

    @WebMethod
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebMethod
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.wangsd.client.User arg0
    );
}
