
package com.wangsd.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-12-19T11:33:36.539+08:00
 * Generated source version: 3.1.4
 * 
 */
 
public class HelloWorld_HelloWorldImplPort_Server{

    protected HelloWorld_HelloWorldImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldImpl();
        String address = "http://192.168.205.74:8080/helloWorld";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloWorld_HelloWorldImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
